#!/usr/bin/env python3
"""docs/conformance.md: the specification's statements the tests name, generated.

Every `[MQTT-x.y.z-n]` (or the section number where the test cites a section) that
appears in tests/conformance is listed with the tests that name it, so "one test per
normative statement the broker claims" is a table that can be read and checked, and
so is what is not covered.

    python3 scripts/coverage.py           # write
    python3 scripts/coverage.py --check   # exit 1 if the committed file differs
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TESTS = ROOT / "tests" / "conformance"

NOT_COVERED = """\
- **QoS 2** in every form: PUBREC, PUBREL, PUBCOMP and a PUBLISH at QoS 2 are refused (`unsupported.*`), and a
  SUBSCRIBE at QoS 2 is granted QoS 1. Nothing in section 4.3.3 is claimed.
- **Keep-alive of a client that never sends PINGREQ but sends other packets**: any packet resets the timer; only the
  silent case is tested.
- **UTF-8 well-formedness of every string field**: tested for the client identifier and topic names with U+0000; the
  decoder rejects ill-formed UTF-8 everywhere, but only the cases above have a named test.
- **Username and password**: accepted and ignored (no authentication in v1, issue #13).
- **`$SYS` topics**: not generated (issue #13); only the rule that a leading wildcard does not match a `$` topic.
- **Message ordering across subscriptions of different QoS** (4.6): only one topic at one QoS is tested.
- **Behaviour of a broker restart**: nothing persists (issue #13); no test, by design.
"""


def main():
    found = {}
    for path in sorted(TESTS.glob("test_*.py")):
        text = path.read_text()
        tests = re.split(r"\n    def (test_\w+)\(self[^)]*\):\n", text)
        # tests[0] is the preamble; then name, body, name, body...
        for name, body in zip(tests[1::2], tests[2::2]):
            for m in re.finditer(r"\[MQTT-(\d+\.\d+\.\d+-\d+)\]", body):
                found.setdefault(m.group(1), set()).add("%s::%s" % (path.name, name))
    def key(s):
        return tuple(int(x) for x in re.split(r"[.-]", s))
    lines = [
        "# Conformance coverage",
        "",
        "Generated by `scripts/coverage.py` from `tests/conformance`; do not edit. Every statement of",
        "MQTT 3.1.1 that a test names (`[MQTT-x.y.z-n]` is the specification's own number) is listed with the",
        "tests that name it. Behaviour with no statement number of its own is covered too (`test_protocol.py`,",
        "`test_rules.py`, `test_differential.py`); this table is what can be traced to the text.",
        "",
        "**Caveat.** The statement numbers were written from memory of the OASIS MQTT 3.1.1 text: this repository has",
        "no copy of the specification and the environment these tests were written in could not fetch it, so a number",
        "may be wrong. A wrong number is corrected in the test that cites it, and this file regenerates.",
        "",
        "| Statement | Tests |",
        "|---|---|",
    ]
    for s in sorted(found, key=key):
        lines.append("| [MQTT-%s] | %s |" % (s, ", ".join("`%s`" % t for t in sorted(found[s]))))
    lines += ["", "## What is not covered", "", NOT_COVERED]
    return "\n".join(lines)


if __name__ == "__main__":
    text = main()
    path = ROOT / "docs" / "conformance.md"
    if "--check" in sys.argv[1:]:
        if not path.exists() or path.read_text() != text:
            print("stale docs/conformance.md (run scripts/coverage.py)")
            sys.exit(1)
        sys.exit(0)
    path.write_text(text)
