#!/usr/bin/env python3
"""The authority report: derived by the compiler, committed, embedded in the
binary, and gated against a ceiling (docs/design.md section 2, gate G4).

For every [[bin]] in cancho.toml:

1. pass 1: `cancho authority <sources> --std --output json`;
2. write manifests/<bin>.authority.json (the committed record) and
   generated/<bin>/built.cho, which holds the report, the JSON Schema
   (schemas/<bin>.v1.json) and the compiler pin as string literals, so the binary
   can print them (`mqtt introspect`);
3. pass 2: derive again with the new generated file and require the same
   report -- the fixed point. A string constant adds no label;
4. require every derived label, spelled with its argument, to be in the bin's
   `allow` list in ceiling.toml, `bounded` true and no foreign symbol, and no
   label in FORBIDDEN whatever the ceiling says.

    python3 scripts/manifest.py            # regenerate, then check
    python3 scripts/manifest.py --check    # change nothing; exit 1 on drift

`--check` also compares what the built binary prints (`build/<bin> introspect`)
with the fresh derivation when the binary exists, so a stale build is caught as
well as a stale file.

The compiler is $CANCHO, or `cancho` on PATH.
"""

import json
import os
import pathlib
import subprocess
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Never allowed, whatever ceiling.toml says: persistence, foreign code, bridging.
FORBIDDEN = {"ffi", "net_out", "fs_read", "fs_write", "file_read", "file_write", "dir_read", "dir_write", "io_read"}


def compiler():
    return os.environ.get("CANCHO", "cancho")


def sources(entry):
    # Dependencies are fetched into build/deps by `cancho install`; the report
    # covers them, since they are part of the program.
    subprocess.run([compiler(), "install"], cwd=ROOT, capture_output=True, text=True)
    files = []
    for s in entry["sources"]:
        p = ROOT / s
        files.extend(sorted(str(x) for x in p.glob("*.cho")) if p.is_dir() else [str(p)])
    files.extend(sorted(str(x) for x in (ROOT / "build" / "deps").glob("*.cho")))
    return files


def derive(files):
    out = subprocess.run([compiler(), "authority", *files, "--std", "--output", "json"],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("cancho authority failed:\n" + out.stdout + out.stderr)
    return json.loads(out.stdout)


def compact(value):
    return json.dumps(value, separators=(",", ":"), ensure_ascii=True)


def literal(text):
    """A cancho string literal: six escapes, no others, one line."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 32:
            sys.exit("a control character cannot be written in a cancho literal")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def generated(report, schema, pin):
    return """edition 5;

module built;

// Generated by scripts/manifest.py -- do not edit. The compiler's authority
// report for this program, its JSON Schema, and the compiler it was written for,
// as `mqtt introspect` prints them.

pub fn authority() -> [] &static [byte] {
    return %s;
}

pub fn schema() -> [] &static [byte] {
    return %s;
}

pub fn compiler() -> [] &static [byte] {
    return %s;
}
""" % (literal(compact(report)), literal(compact(schema)), literal(pin))


def label_text(label):
    if label["argument"] is None:
        return label["name"]
    return '%s("%s")' % (label["name"], label["argument"])


def gate(name, report, ceilings):
    problems = []
    ceiling = ceilings.get(name)
    if ceiling is None:
        return ["%s: no ceiling in ceiling.toml" % name]
    allowed = set(ceiling.get("allow", []))
    if not report.get("bounded", False):
        problems.append("%s: bounded is false" % name)
    if report.get("foreign_symbols"):
        problems.append("%s: foreign symbols %s" % (name, report["foreign_symbols"]))
    for label in report["labels"]:
        text = label_text(label)
        if label["name"] in FORBIDDEN:
            problems.append("%s: %s is forbidden to the broker" % (name, text))
        if text not in allowed:
            problems.append("%s: %s is not within the ceiling in ceiling.toml" % (name, text))
    return problems


def printed(name):
    binary = ROOT / "build" / name
    if not binary.exists():
        return None
    out = subprocess.run([str(binary), "introspect"], capture_output=True, text=True)
    if out.returncode != 0:
        return "exit %d" % out.returncode
    return json.loads(out.stdout)["authority"]


def main():
    check = "--check" in sys.argv[1:]
    with open(ROOT / "cancho.toml", "rb") as f:
        project = tomllib.load(f)
    with open(ROOT / "ceiling.toml", "rb") as f:
        ceilings = tomllib.load(f)
    problems = []
    for entry in project.get("bin", []):
        name = entry["name"]
        files = sources(entry)
        first = derive(files)
        record = ROOT / "manifests" / ("%s.authority.json" % name)
        built = ROOT / "generated" / name / "built.cho"
        record_text = json.dumps(first, indent=2) + "\n"
        schema = json.loads((ROOT / "schemas" / ("%s.v1.json" % name)).read_text())
        built_text = generated(first, schema, project["package"]["cancho"])
        if check:
            if not record.exists() or record.read_text() != record_text:
                problems.append("%s: %s is not the compiler's report" % (name, record.relative_to(ROOT)))
            if not built.exists() or built.read_text() != built_text:
                problems.append("%s: %s is stale" % (name, built.relative_to(ROOT)))
            embedded = printed(name)
            if embedded is not None and embedded != first:
                problems.append("%s: build/%s introspect prints an authority that is not the compiler's (a stale build?)" % (name, name))
        else:
            record.parent.mkdir(exist_ok=True)
            record.write_text(record_text)
            built.parent.mkdir(parents=True, exist_ok=True)
            built.write_text(built_text)
            second = derive(files)
            if second != first:
                problems.append("%s: no fixed point -- embedding the report changed the authority" % name)
        problems.extend(gate(name, first, ceilings))
        print("%-6s %s" % (name, ", ".join(label_text(l) for l in first["labels"]) or "(nothing)"))
    for p in problems:
        print("FAIL " + p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
