#!/usr/bin/env python3
"""docs/side-by-side.md: this broker and Mosquitto, running the same scenarios, with what each client saw.

The scenarios are the ones the differential tests run (tests/conformance/test_differential.py and
test_auth_differential.py), so the document and the gate cannot disagree: it is generated by running both brokers.

    python3 scripts/side_by_side.py           # rewrite docs/side-by-side.md
    python3 scripts/side_by_side.py --check   # change nothing; exit 1 if the file is stale (CI)

Needs build/mqtt, mosquitto and mosquitto_passwd.
"""

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tests" / "conformance"))

from harness import Broker, user_line  # noqa: E402
import test_auth_differential as ad  # noqa: E402
import test_differential as td  # noqa: E402

OUT = ROOT / "docs" / "side-by-side.md"

# Why each written-down difference exists. The facts are asserted by the tests; the reasons are the design's.
WHY = {
    "overlapping filters with different QoS": "A client whose filters overlap gets one copy. This broker sends it at the highest QoS "
                                              "granted (3.3.5); Mosquitto at the QoS of the first match in its trie.",
    "qos2 delivery before PUBREL": "This broker routes an inbound QoS 2 message when its PUBLISH arrives and remembers the identifier "
                                   "until PUBREL (method A, design section 7a); Mosquitto holds it until PUBREL (method B). "
                                   "4.3.3 allows both.",
}


def say(op):
    k = op[0]
    if k in ("connect", "connect31"):
        extra = ("a clean" if op[2] else "a persistent") + " session"
        if k == "connect31":
            extra += ", MQTT 3.1"
        if len(op) > 3 and op[3]:
            extra += ", will %s=%r" % (op[3][0], op[3][1].decode())
        return "%s connects (%s)" % (op[1], extra)
    if k == "subscribe":
        return "%s subscribes %s" % (op[1], ", ".join("`%s` at QoS %d" % f for f in op[2]))
    if k == "unsubscribe":
        return "%s unsubscribes %s" % (op[1], ", ".join("`%s`" % f for f in op[2]))
    if k == "publish":
        return "%s publishes `%s` %r at QoS %d%s" % (op[1], op[2], op[3].decode(), op[4], ", retained" if op[5] else "")
    if k == "disconnect":
        return "%s disconnects %s" % (op[1], "cleanly" if op[2] else "abruptly")
    if k == "begin2":
        return "%s sends a QoS 2 PUBLISH of `%s` and does not release it" % (op[1], op[2])
    if k == "release2":
        return "%s releases it (PUBREL)" % op[1]
    return str(op)


def event(e):
    if e[0] == "connack":
        return "CONNACK %d%s" % (e[2], ", session present" if e[1] else "")
    if e[0] == "suback":
        return "SUBACK %s" % ",".join(map(str, e[1]))
    if e[0] == "unsuback":
        return "UNSUBACK"
    if e[0] == "pub":
        return "receives `%s` %r QoS %d%s" % (e[1], e[2].decode(), e[3], " retained" if e[4] else "")
    return e[0]


def seen(history):
    return "<br>".join("**%s**: %s" % (name, "; ".join(event(e) for e in events)) for name, events in history.items() if events)


def both(ops):
    mine, theirs = Broker(), td.MosquittoBroker()
    try:
        return td.play(mine.port, ops), td.play(theirs.port, ops)
    finally:
        mine.__exit__(None, None, None)
        theirs.stop()


def version():
    out = subprocess.run([td.MOSQUITTO, "-h"], capture_output=True, text=True).stdout.splitlines()
    return out[0].replace("mosquitto version ", "").strip() if out else "?"


def document():
    lines = [
        "# cancho-mqtt beside Mosquitto",
        "",
        "*Generated by `scripts/side_by_side.py`; CI fails if it is stale. Do not edit by hand.*",
        "",
        "The same scenario is played against this broker and against Mosquitto %s, and what each client saw is compared: not the "
        "bytes on the wire, and not timing. It is a record of behaviour on these scenarios, not a claim about all of either "
        "program. The scenarios are the ones `tests/conformance/test_differential.py` and `test_auth_differential.py` run, "
        "plus generated ones (40 fixed seeds in every CI run) that are not listed here." % version(),
        "",
        "## Where they agree",
        "",
    ]
    for name, ops in td.SCRIPTS.items():
        if isinstance(ops, tuple):
            continue
        mine, theirs = both(ops)
        assert mine == theirs, "the brokers disagree on %s" % name
        lines += ["### %s" % name, "", "\n".join("%d. %s" % (i + 1, say(o)) for i, o in enumerate(ops)), "",
                  "Both: %s" % seen({k: v for k, v in mine.items() if v}), ""]
    lines += ["## Where they differ, on purpose", "",
              "Each difference is asserted as a difference by the tests: one nobody wrote down is a failure, and so is a written-down "
              "one that went away.", ""]
    for name, (ops, ours, theirs) in td.KNOWN_DIFFERENCES.items():
        mine, other = both(ops)
        assert {k: v for k, v in mine.items() if v} == ours and {k: v for k, v in other.items() if v} == theirs, name
        lines += ["### %s" % name, "", WHY.get(name, ""), "", "\n".join("%d. %s" % (i + 1, say(o)) for i, o in enumerate(ops)), "",
                  "| cancho-mqtt | Mosquitto |", "|---|---|", "| %s | %s |" % (seen(ours), seen(theirs)), ""]
    lines += ["## Logins", "",
              "One CONNECT with the given credentials, to a broker holding one user, `alice`. This broker is run with "
              "`--auth stdin`; Mosquitto with `password_file` and `allow_anonymous false`. Mosquitto answers CONNACK 5 to every "
              "login it does not accept; this broker follows MQTT 3.1.1 (3.2.2.3) and answers 4 where the user name or password is "
              "wrong, and 5 where there is no user name (design section 7c).", "",
              "| The client sends | cancho-mqtt | Mosquitto | |", "|---|---|---|---|"]
    mine_broker = Broker(users=user_line(ad.USER, ad.PASSWORD))
    theirs_broker = td.MosquittoBroker(users=[(ad.USER, ad.PASSWORD)])
    try:
        for label, (creds, ours, theirs) in ad.CASES.items():
            got_mine, got_theirs = ad.probe(mine_broker.port, creds), ad.probe(theirs_broker.port, creds)
            assert (got_mine, got_theirs) == (ours, theirs), label
            show = lambda r: "CONNACK %d, connection %s" % r
            lines.append("| %s | %s | %s | %s |" % (label, show(got_mine), show(got_theirs), "same" if got_mine == got_theirs else "**differs**"))
        mine_takeover, theirs_takeover = ad.takeover(mine_broker.port), ad.takeover(theirs_broker.port)
    finally:
        mine_broker.__exit__(None, None, None)
        theirs_broker.stop()
    lines += ["", "A second connection that uses a live session's client identifier with a wrong password: this broker answers "
              "CONNACK %d and Mosquitto CONNACK %d; in both the first connection stays up (%s) and its will is not published (%s)."
              % (mine_takeover[0], theirs_takeover[0], "yes" if mine_takeover[1] and theirs_takeover[1] else "NO",
                 "yes" if not mine_takeover[2] and not theirs_takeover[2] else "NO"), ""]
    return "\n".join(lines)


def main():
    if not td.MOSQUITTO or not (ROOT / "build" / "mqtt").exists():
        sys.exit("side-by-side: needs build/mqtt and mosquitto")
    text = document()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print("side-by-side: docs/side-by-side.md is stale (run scripts/side_by_side.py)")
            sys.exit(1)
        return
    OUT.write_text(text)


if __name__ == "__main__":
    main()
